### ISSUE TITLE
Add config support

### ISSUE THREAD

**Issue by BlackPhrase** [BlackPhrase/V-Engine#4]
Should it be INI or XML?

**Comment by kennyrkun** [comment]
You might look into [this](https://github.com/SFML/SFML/wiki/Source:-Settings-Parser).

I use it for my projects.

**Comment by BlackPhrase** [comment]
Looks like it doesn't support sections

**Comment by BlackPhrase** [comment]
It's like
```
[Graphics]
nWidth = 640
nHeight = 480
```
So instead of key-value its section:key-value

**Comment by kennyrkun** [comment]
It could be, I suppose if the config is large enough. Personally I don't think it's useful, so whatever you want will be fine, just make it fantastic.

**Comment by BlackPhrase** [comment]
I want to clarify some things

It currently requires to access keys via "Section:Key" syntax (ex: "GeneralSection:SomeKey")
I dunno if non-sectioned syntax will be required

Currently, the config interface only supports string setters/getters
Do we need int/float/bool getters? You can use functions such as atoi for that yourself. If we're using mentioned getters that will be done internally
Also, do we need a default string value in getter? I mean, do we need to support a custom value, that will be returned in case no value was found?

```cpp
struct IConfig
{
    virtual const char *GetString(const char *key) const = 0; // will return "" if not found
    virtual const char *GetString(const char *key, const char *defvalue) const = 0; // will return defvalue if not found
};
```

**Comment by kennyrkun** [comment]
I don't think that we need sections for the configs. And if it's really necessary, we can just use comments or set the name of the key to "Section:Key" = "value". And if we do that, there's really no reason not use the small class I provided. It supports all default types, and can easily be extended to hold anything else. I extended it myself to support `sf::Vector2` & `3`, as well as `sf::Color`

**Comment by BlackPhrase** [comment]
>"Section:Key" = "value"

And how much it would readable?

```
sound:blah = 1
sound:blah2 = 2
sound:blah3 = 3

graphics:blah = 4
graphics:blah2 = 5
```

vs

```
[sound]
blah = 1
blah2 = 2
blah3 = 3

[graphics]
blah3 = 6
```

**Comment by kennyrkun** [comment]
I feel like sections are unnecessary. Since, I believe that it should be split up. If you even do need to organise things like that, they should probably be split up into their own files

```
sound.cfg
graphics.cfg
game.cfg
```

I feel like it's perfectly readable, if not slightly more verbose. And, I believe adding the section functionality to the settings parser I suggested. If you can't tell, I believe strongly that we should try to keep things as simple as possible, and not recreate our own stuff wherever possible.

Perhaps the engine should have a more modular approach to settings. That way, whoever is using the engine can use their own implementation, and just tell engine what keys to look for. Perhaps something like `engine->pvar->get(string name, string filelocation, std::function getfunction`

**Comment by BlackPhrase** [comment]
I will think about it

**Comment by BlackPhrase** [comment]
>I believe strongly that we should try to keep things as simple as possible

>If you even do need to organise things like that, they should probably be split up into their own files

You contradict yourself
